load OBJ-FFT

mod PRETTY-PRINT is
  pr OBJ-FFT-SEARCH .

  sort Heading .
  sort Printing .
  
  op p : String -> Printing .
  op 0_ : Printing -> Printing [format (n d d)].
  op 1_ : Printing -> Printing [format (n sss d)].
  op 2_ : Printing -> Printing [format (n ssssss d)].
  op __ : Printing Printing -> Printing .
  
  op print-config : Configuration -> Printing .
  op print-object : Object -> Printing . 
endm
